// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './shots/ai-1/Ai1Door';
import Shot1, { compositionConfig as cfg1 } from './shots/dyatlov-pass-1/DyatlovEp1Expedition';
import Shot2, { compositionConfig as cfg2 } from './shots/dyatlov-pass-2/DyatlovEp2Tent';
import Shot3, { compositionConfig as cfg3 } from './shots/dyatlov-pass-3/DyatlovEp3Search';
import Shot4, { compositionConfig as cfg4 } from './shots/dyatlov-pass-4/DyatlovEp4Ravine';
import Shot5, { compositionConfig as cfg5 } from './shots/dyatlov-pass-5/DyatlovEp5Science';
import Shot6, { compositionConfig as cfg6 } from './shots/hybrid-demo/HybridDemo';
import Shot7, { compositionConfig as cfg7 } from './shots/roopkund-lake-1-hi/RoopkundEp1LakeOfBonesHi';
import Shot8, { compositionConfig as cfg8 } from './shots/roopkund-lake-1/RoopkundEp1LakeOfBones';
import Shot9, { compositionConfig as cfg9 } from './shots/roopkund-lake-1/RoopkundLake1Thumbnail';
import Shot10, { compositionConfig as cfg10 } from './shots/roopkund-lake-2-hi/RoopkundEp2TheStormHi';
import Shot11, { compositionConfig as cfg11 } from './shots/roopkund-lake-2/RoopkundEp2TheStorm';
import Shot12, { compositionConfig as cfg12 } from './shots/roopkund-lake-3/RoopkundEp3WhoWereThey';
import Shot13, { compositionConfig as cfg13 } from './shots/roopkund-lake-4/RoopkundEp4AThousandYearsApart';
import Shot14, { compositionConfig as cfg14 } from './shots/short-10/Short10Fees';
import Shot15, { compositionConfig as cfg15 } from './shots/short-11/Short11Map';
import Shot16, { compositionConfig as cfg16 } from './shots/short-12/Short12Orbit';
import Shot17, { compositionConfig as cfg17 } from './shots/short-1/Short1Chess';
import Shot18, { compositionConfig as cfg18 } from './shots/short-2/Short2Math';
import Shot19, { compositionConfig as cfg19 } from './shots/short-3/Short3Algo';
import Shot20, { compositionConfig as cfg20 } from './shots/short-4/Short4Reflog';
import Shot21, { compositionConfig as cfg21 } from './shots/short-5/Short5Monty';
import Shot22, { compositionConfig as cfg22 } from './shots/short-6/Short6Sheet';
import Shot23, { compositionConfig as cfg23 } from './shots/short-7/Short7Kids';
import Shot24, { compositionConfig as cfg24 } from './shots/short-8/Short8Phish';
import Shot25, { compositionConfig as cfg25 } from './shots/short-9/Short9Chords';
import Shot26, { compositionConfig as cfg26 } from './shots/vox-1/Vox1Coffee';
import Shot27, { compositionConfig as cfg27 } from './shots/voynich-manuscript-1/VoynichEp1UnbreakableCodex';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
  { Comp: Shot5 as React.FC, config: cfg5 },
  { Comp: Shot6 as React.FC, config: cfg6 },
  { Comp: Shot7 as React.FC, config: cfg7 },
  { Comp: Shot8 as React.FC, config: cfg8 },
  { Comp: Shot9 as React.FC, config: cfg9 },
  { Comp: Shot10 as React.FC, config: cfg10 },
  { Comp: Shot11 as React.FC, config: cfg11 },
  { Comp: Shot12 as React.FC, config: cfg12 },
  { Comp: Shot13 as React.FC, config: cfg13 },
  { Comp: Shot14 as React.FC, config: cfg14 },
  { Comp: Shot15 as React.FC, config: cfg15 },
  { Comp: Shot16 as React.FC, config: cfg16 },
  { Comp: Shot17 as React.FC, config: cfg17 },
  { Comp: Shot18 as React.FC, config: cfg18 },
  { Comp: Shot19 as React.FC, config: cfg19 },
  { Comp: Shot20 as React.FC, config: cfg20 },
  { Comp: Shot21 as React.FC, config: cfg21 },
  { Comp: Shot22 as React.FC, config: cfg22 },
  { Comp: Shot23 as React.FC, config: cfg23 },
  { Comp: Shot24 as React.FC, config: cfg24 },
  { Comp: Shot25 as React.FC, config: cfg25 },
  { Comp: Shot26 as React.FC, config: cfg26 },
  { Comp: Shot27 as React.FC, config: cfg27 },
];
